### ISSUE TITLE
Calculation of totals has been disabled 

### ISSUE THREAD

**Issue by 42Cyborg** [NerdyGamer05/CanvasGradesPro#1]
As far as I can tell, as it is, this does not allow calculations to be set up if a professor has the calculation of totals disabled, is there a way to override that locally and manually enter the grade breakdowns?

**Comment by jpatel2005** [comment]
Can you be a bit more specific (and possibly provide a screenshot)? I'm not really sure what you're talking about

**Comment by 42Cyborg** [comment]
<img width="231" alt="Screenshot 2024-09-19 at 8 32 38 AM" src="https://github.com/user-attachments/assets/94b78602-1efa-42f3-9b97-ec5ef0d814c5">

I have noticed that this works great on most of my classes, however, there are some classes that it doesn't show up at all, like this one. I would be happy to provide more info/data if you need it, but it seems to be that it is just not loading on some pages depending on some canvas setting set by the professor.

Thanks for your reply! I very much like your extension!

**Comment by jpatel2005** [comment]
Thanks for the reply. As for your issue, I haven't had a chance to test my extension on a course where the instructor blocks the grade, so I apologize that you are facing this issue.

As for solving this issue, may I first ask you to check the console tab within the inspect menu. To access the Inspect Menu, right-click on your screen and select **Inspect**. From here, you should see a tab near the top labeled **Console**. Click this tab, and check to see if you have errors that say `content_script.js` on the right side. If so, then please take a screenshot of those errors so that I can diagnose your issue.

In addition to above, could you also highlight the text that says "Calculation of totals has been disabled", right-click it, then select **Inspect*? From there, please take a screenshot of the entire inspect menu so that I can see if there's something wrong.

And lastly, could you provide another screenshot of the extension working for at least one of your other classes? It can be of the entire page or just the right side.

If there were no issues in the console, then please let me know so that I can have you test something else. Sorry again for the inconvenience.

**Comment by 42Cyborg** [comment]
no inconvenience at all! you are doing me a huge favor by looking into this, so no need to apologize

TypeError: grading_standard is undefined
<img width="1512" alt="Screenshot 2024-09-19 at 1 20 56 PM" src="https://github.com/user-attachments/assets/61301026-a955-4c4a-859a-b4a9329357ed">

<img width="1512" alt="Screenshot 2024-09-19 at 1 26 30 PM" src="https://github.com/user-attachments/assets/e656aa98-146f-431d-b497-0117a95acc0d">

this one works but can't calculate a total
<img width="164" alt="Screenshot 2024-09-19 at 1 27 45 PM" src="https://github.com/user-attachments/assets/61cc5bc1-b2ae-4d0a-a28e-ddf70df0ee77">

this one works fine:
<img width="151" alt="Screenshot 2024-09-19 at 1 29 59 PM" src="https://github.com/user-attachments/assets/dbd8f9a3-7643-41ec-9a33-53d568a37adc">

**Comment by jpatel2005** [comment]
Thank you for getting back to me so quickly. To help me understand what is happening, could you do the following things:
First, paste the following code into your console, 
```js
course = await (await fetch(`/api/v1/courses/110205`, {
    method: 'GET'
})).json();
console.log('grading_standard_id: ' + course.grading_standard_id);
json = (await (await fetch(`/api/v1/courses/110205/grading_standards/${course.grading_standard_id}`)).json());
console.log(json);
```
After pasting the code into your console, press enter and please send a screenshot of the response. In addition, for the last response (should start with "Object" and say `instrument.js` on the right side), please right-click the box and select "Copy Object", and attach that in your response, along with a screenshot of the entire response.

Thank you for your cooperation.

**Comment by 42Cyborg** [comment]
<img width="1512" alt="Screenshot 2024-09-20 at 9 59 20 AM" src="https://github.com/user-attachments/assets/b340428e-956b-44dd-bde9-49c84372a614">

{
  "errors": [
    {
      "message": "The specified resource does not exist."
    }
  ]
}

<img width="1512" alt="Screenshot 2024-09-20 at 10 00 59 AM" src="https://github.com/user-attachments/assets/47f6930a-57f6-4e5b-9a4d-f0b9d52758ba">

Please let me know if there is anything else I can do to help you

**Comment by jpatel2005** [comment]
I believe I understand the issue now. It appears as if though your instructor provided a grading standard for the class grades to follow (, however, it is not accessible by you (or any other student) due to the grades being hidden.

One final thing you could do for me is to execute the following code in your console (same way as before):
```js
json = (await (await fetch(`/api/v1/courses/110205/grading_standards`)).json());
console.log(json);
```
After pasting the code into your console, press enter and please send a screenshot of the response. In addition, for the last response (should start with "Object" and say `instrument.js` on the right side), please right-click the box and select "Copy Object", and attach that in your response, along with a screenshot of the entire response.

---

The instructor grades still being shown as hidden (instead of the grade being calculated) is another issue, however, I believe I know how to solve this issue.

I plan on fixing these issues (along with some other issues that I've found), as well as completing the GPA calculator feature that I've been working on, and publishing these updates sometime this weekend. This means that you'll probably have to wait up to a week for this to fixed since the extension has to be re-approved for every update (however long this takes is out of my control).

Thanks for assisting me in debugging this issue and I apologize for any inconvenience.

**Comment by 42Cyborg** [comment]
<img width="1512" alt="Screenshot 2024-09-20 at 11 27 13 AM" src="https://github.com/user-attachments/assets/a51bda73-cca8-4b6c-8dd2-e58738753e7f">

Array object appears to be empty:
[]

<img width="1512" alt="Screenshot 2024-09-20 at 11 28 31 AM" src="https://github.com/user-attachments/assets/2e726042-9665-4b39-8cc9-75e2bf0b1f8f">

No rush on any of this, I am more than happy to assist with more debugging in future, just let me know if there is anything I can do to help you

**Comment by jpatel2005** [comment]
I believe that I have fixed the bugs that you were experiencing, however, I have yet to fix other bugs that I discovered while doing my own testing, and I have also yet to complete the GPA calculator feature.

Because of this, the publishing of the update will have to be delayed to sometime later this week or possibly even span into next weekend. If this is the case, I may just release an update patching bugs that I have fixed then release another update in the future which will patch additional bugs as well as release the GPA calculator feature.

Sorry for the inconvenience.

**Comment by jpatel2005** [comment]
Sorry for the extreme delay. ~~Version 1.0.3~~ Version 1.0.4 has been published, which should fix your bug, as well as introduce the GPA calculator feature. 

If you are still facing issues, please let me know by creating another issue so that I can try fix any issues you have before publishing another version.

**Comment by 42Cyborg** [comment]
Thank you! It works great.
